# Generated by Django 5.0.6 on 2024-06-20 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_Material', models.IntegerField(primary_key=True, serialize=False)),
                ('Calidad', models.TextField(null=True)),
                ('Tamaño', models.TextField(null=True)),
                ('Color', models.TextField(null=True)),
                ('Tipo', models.TextField(null=True)),
                ('Nombre', models.TextField(null=True)),
                ('Precio', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_Producto', models.IntegerField(primary_key=True, serialize=False)),
                ('Precio', models.FloatField(null=True)),
                ('Tamaño', models.IntegerField(null=True)),
                ('Color', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDePago',
            fields=[
                ('id_de_Pago', models.IntegerField(primary_key=True, serialize=False)),
                ('Efectivo', models.FloatField(null=True)),
                ('Tarjeta', models.FloatField(null=True)),
                ('Transferencia', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_Usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('Primer_nombre', models.TextField(null=True)),
                ('Segundo_nombre', models.TextField(null=True)),
                ('Primer_apellido', models.TextField(null=True)),
                ('Segundo_apellido', models.TextField(null=True)),
                ('Tipo_documento', models.TextField(null=True)),
                ('Documento', models.BigIntegerField(null=True)),
                ('Direccion', models.TextField(null=True)),
                ('Telefono', models.FloatField(null=True)),
                ('Correo', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_Compra', models.IntegerField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(default=None, null=True)),
                ('Valor', models.BigIntegerField(default=None, null=True)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagardecors.tipodepago')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeProducto',
            fields=[
                ('id_Tipo_de_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(null=True)),
                ('Referencia', models.TextField(null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagardecors.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_Venta', models.IntegerField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Valor', models.FloatField(null=True)),
                ('tipo_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagardecors.tipodepago')),
            ],
        ),
    ]
