# Generated by Django 4.1.3 on 2024-07-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagardecors', '0002_producto_descripcion_producto_imagen_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
