# Generated by Django 4.1.3 on 2024-07-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagardecors', '0004_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
    ]
